const clothes = [
    {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
        img: 'https://www.consortium.co.uk/media/catalog/product/cache/1/image/1000x/af097278c5db4767b0fe9bb92fe21690/p/o/polar-skate-co-big-boy-denim-jeans-dark-blue-psc-f20-bigboyjeans-dblu_0000_cat.jpg',
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 70,
        owned_by_me: true,
        img: 'https://derschutze.com/cdn/shop/products/2023_02_06_2_1.jpg?v=1675766077&width=2200'
    },    
{
        Type_of_clothes: 'crewneck',
        color: 'light brown',
        name_of_peice: 'Essentials crewn neck beige',
        seller: 'Essentials',
        style: ['street wear','basic'],
        Price_in_usd: 90,
        owned_by_me: true,
        img:'https://cdn.shoplightspeed.com/shops/652568/files/52243356/image.jpg'

    },
    {
        Type_of_clothes: 'shoes',
        color:'black',
        name_of_peice: 'DrkShdw hightop zip ups',
        seller: 'Rickownes',
        style: ['street wear','hypebeast','highfashion'],
        Price_in_usd: 1100,
        owned_by_me:  true,
        img:'https://cdnc.lystit.com/photos/1018-2015/09/14/rick-owens-drkshdw-black-side-zip-hi-top-sneakers-product-0-668688035-normal.jpeg'
    },     
    {
        Type_of_clothes: 'Hoodie',
        color: 'black',
        name_of_peice: 'Carhartt K288',
        seller: 'Carhart',
        style: ['street wear','skater','work wear'],
        Price_in_usd: 55,
        owned_by_me: true,
        img:'https://th.bing.com/th/id/R.73af1ba2c8a89773dbb3df17d18d559a?rik=EszCWnLbNR4yQg&riu=http%3a%2f%2fimage.sportsmansguide.com%2fadimgs%2fl%2f1%2f170017i11_ts.jpg&ehk=a9XITsHAo5cOX0KxRn3uyJYSnistqtCDKHS9sMqLk84%3d&risl=&pid=ImgRaw&r=0',
    },
    {
        Type_of_clothes: 'shirt',
        color:'white',
        name_of_peice: 'PEACE FOR ALL',
        seller: 'UniQlo',
        style: ['street wear'],
        Price_in_usd: 24,
        owned_by_me: true,
        img:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/457869/item/goods_00_457869.jpg?width=700',
    },     

    {
        Type_of_clothes: 'jeans',
        color: 'light blue',
        name_of_peice: 'Baggy Light blue denim',
        seller: 'Gone pants',
        style: ['street wear','skater'],
        Price_in_usd: 75,
        owned_by_me: true,
        img: 'https://images.squarespace-cdn.com/content/v1/616311642ac74d0c65727a05/1692568923082-R9ULILLTJUKYXO3CFHVI/DSC03035.jpg?format=750',
    },
    {
        Type_of_clothes: 'shirt',
        color:'black',
        name_of_peice: 'Kaws UT',
        seller: 'UniQlo',
        style: ['street wear'],
        Price_in_usd: 25,
        owned_by_me: true,
        img:'https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/467775/sub/goods_467775_sub14.jpg?width=750',
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Carhartt Wip Marlow Pant Jeans',
        seller: 'Carhartt',
        style: ['street wear','skater', 'work wear'],
        Price_in_usd: 55,
        owned_by_me: true,
        img:'https://cdn.shopify.com/s/files/1/2577/9994/products/carhartt-wip-pontiac-pant-relaxed-straight-mens-jeans-blue-one-wash-w30-l32-i029210012y30r-carhartt-wip-jeans-29815022485698@2x.jpg?v=1628847456',
    },
    {
        Type_of_clothes: 'shoes',
        color:'white',
        name_of_peice: 'Air Force one',
        seller: 'Nike',
        style: ['street wear','skater','basic'],
        Price_in_usd: 100,
        owned_by_me: true,
        img:'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-mens-shoes-jBrhbr.png',
    },    

    {
        Type_of_clothes: 'shoes',
        color: 'black',
        name_of_peice: 'Converse High top',
        seller: 'Converse',
        style: ['street wear','skater'],
        Price_in_usd: 70,
        owned_by_me: true,
        img: 'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw96d51de8/images/a_08/M9160_A_08X1.jpg?sw=406',
    },
    {
        Type_of_clothes: 'shoes',
        color:'black',
        name_of_peice: 'converse low top',
        seller: 'converse',
        style: ['street wear'],
        Price_in_usd: 70,
        owned_by_me: true,
        img:'https://static.nike.com/a/images/t_default/318d7fed-d5bc-4a0a-8956-3e308976c50e/converse-chuck-taylor-all-star-low-top-unisex-shoes-NLRAok.png',
    },     
    {
        Type_of_clothes: 'hoodie',
        color:'black',
        name_of_peice: 'essentials hoodie',
        seller: 'Essentials',
        style: ['street wear','basic'],
        Price_in_usd: 90,
        owned_by_me: false,
        img:'https://images.stockx.com/images/FEAR-OF-GOD-ESSENTIALS-Pull-Over-Hoodie-SS21-Black-Stretch-Limo.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1620853883',
    },    
    {
        Type_of_clothes: 'shoes',
        color: 'beige',
        name_of_peice: 'Sail off white jordan 4',
        seller: 'Jordan',
        style: ['street wear','hypebeast'],
        Price_in_usd: 200,
        owned_by_me: false,
        img:'https://sneakernews.com/wp-content/uploads/2020/07/off-white-jordan-4-release-reminder-7.jpg',
    },
 {
        Type_of_clothes: 'hoodie',
        color: 'beige',
        name_of_peice: 'Stussy 8 ball fleece',
        seller: 'Stussy',
        style: ['street wear','skater'],
        Price_in_usd: 500,
        owned_by_me: false,
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROCEkNN2raJCkrgJVUHtUBUZMXInGB0MUNqNuOCWO8e9aw_CjykwKQ_OtVp_Q2r5yUbQ4&usqp=CAU',
    },
    {
        Type_of_clothes: 'hoodie',
        color:'pink',
        name_of_peice: 'Sp5der P*nk Hoodie',
        seller: 'Sp5der',
        style: ['street wear','hypebeast'],
        Price_in_usd: 400,
        owned_by_me: false,
        img:'https://image.goat.com/transform/v1/attachments/product_template_additional_pictures/images/091/128/523/original/814506_01.jpg.jpeg?action=crop&width=750',
    }, 
   
]

export {clothes}