const clothes = [
    {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 70,
        owned_by_me: true,
    },    
{
        Type_of_clothes: 'crewneck',
        color: 'light brown',
        name_of_peice: 'Essentials crewn neck beige',
        seller: 'Essentials',
        style: ['street wear','basic'],
        Price_in_usd: 90,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shoes',
        color:'black',
        name_of_peice: 'DrkShdw hightop zip ups',
        seller: 'Rickownes',
        style: ['street wear','hypebeast','highfashion'],
        Price_in_usd: 1100,
        owned_by_me: true,
    },     
    {
        Type_of_clothes: 'Hoodie',
        color: 'black',
        name_of_peice: 'Carhart work hoodie',
        seller: 'Carhart',
        style: ['street wear','skater','work wear'],
        Price_in_usd: 50,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'white',
        name_of_peice: 'PEACE FOR ALL',
        seller: 'UniQlo',
        style: ['street wear'],
        Price_in_usd: 24,
        owned_by_me: true,
    },     
    {
        Type_of_clothes: 'jeans',
        color: 'white',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: true,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: true,
    }, 
   
]