const clothes = [
    {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 70,
        owned_by_me: True,
    },    
{
        Type_of_clothes: 'crewneck',
        color: 'light brown',
        name_of_peice: 'Essentials crewn neck beige',
        seller: 'Essentials',
        style: ['street wear','basic'],
        Price_in_usd: 90,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shoes',
        color:'black',
        name_of_peice: 'DrkShdw hightop zip ups',
        seller: 'Rickownes',
        style: ['street wear','hypebeast','highfashion'],
        Price_in_usd: 1100,
        owned_by_me:  True,
    },     
    {
        Type_of_clothes: 'Hoodie',
        color: 'black',
        name_of_peice: 'Carhartt K288',
        seller: 'Carhart',
        style: ['street wear','skater','work wear'],
        Price_in_usd: 55,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'white',
        name_of_peice: 'PEACE FOR ALL',
        seller: 'UniQlo',
        style: ['street wear'],
        Price_in_usd: 24,
        owned_by_me: True,
    },     
    {
        Type_of_clothes: 'jeans',
        color: 'light blue',
        name_of_peice: 'Baggy Light blue denim',
        seller: 'Gone pants',
        style: ['street wear','skater'],
        Price_in_usd: 75,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'black',
        name_of_peice: 'Kaws UT',
        seller: 'UniQlo',
        style: ['street wear'],
        Price_in_usd: 25,
        owned_by_me: True,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Carhartt Wip Marlow Pant Jeans',
        seller: 'Carhartt',
        style: ['street wear','skater', 'work wear'],
        Price_in_usd: 55,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shoes',
        color:'white',
        name_of_peice: 'Air Force one',
        seller: 'Nike',
        style: ['street wear','skater','basic'],
        Price_in_usd: 100,
        owned_by_me: True,
    },    
    {
        Type_of_clothes: 'shoes',
        color: 'black',
        name_of_peice: 'Converse High top',
        seller: 'Converse',
        style: ['street wear','skater'],
        Price_in_usd: 70,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shoes',
        color:'black',
        name_of_peice: 'converse low top',
        seller: 'converse',
        style: ['street wear'],
        Price_in_usd: 70,
        owned_by_me: True,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: True,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: True,
    },     {
        Type_of_clothes: 'jeans',
        color: 'blue',
        name_of_peice: 'Big Boy jeans',
        seller: 'Polar Skate Co.',
        style: ['street wear','skater'],
        Price_in_usd: 120,
        owned_by_me: True,
    },
    {
        Type_of_clothes: 'shirt',
        color:'dark purple',
        name_of_peice: 'valentines day',
        seller: 'Derschutze',
        style: ['street wear'],
        Price_in_usd: 60,
        owned_by_me: True,
    }, 
   
]